# client/netlify.toml

# ==================================================
#  THIS IS THE NEW TEST RULE
# ==================================================
[[redirects]]
  from = "/test"
  to = "https://www.google.com"
  status = 302 # This is a temporary redirect
# ==================================================

# This is the original proxy rule
[[redirects]]
  from = "/api/*"
  to = "https://gympro-api.onrender.com/api/:splat"
  status = 200
  force = true 

# This is the SPA fallback rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200