# client/netlify.toml

# This rule proxies all requests from /api/* on your Netlify site
# to your Render API server.
[[redirects]]
  from = "/api/*"
  # THE FIX: We are now pointing to the root of the Render URL.
  # The full path from the original request will be appended.
  to = "https://gympro-api.onrender.com/:splat" 
  status = 200
  force = true
  
# This is the fallback rule for single-page applications.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200