# In ROOT directory: netlify.toml

# API proxy rule - This MUST come first.
[[redirects]]
  from = "/api/*"
  # THIS IS THE CORRECTED URL
  to = "https://gymapp-yqzc.onrender.com/api/:splat" 
  status = 200
  force = true 

# SPA fallback rule - This MUST come last.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200